plugins {
    id 'com.android.application'
}

android {
    namespace 'com.wangkai.passwallcontrol'
    compileSdk 35

    defaultConfig {
        applicationId 'com.wangkai.passwallcontrol'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.0.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
